### PR TITLE
Add bugzilla.mozilla.org and bugzilla-dev.allizom.org to production notification list

### PR DESCRIPTION
**Pull request by dklawren**

### CODE REVIEW

**Comment by floatingatoll** [comment]
Hi @dklawren, we'd like to get additional context for the work that's driving this request. Gene asked the websre team to review and we aren't yet familiar with what's being done here, and I'm hoping you can help. Is there an upstream BMO issue, or a document or even just a Slack discussion, that we could review to gain a better understanding of this request?

Also, a warning. This component of the IAM system is not designed to be resilient against transient errors, so we also need to confirm with you that it's acceptable for these RP notifications to be lossy. If you're already familiar with this concern, then that's a very brief confirmation; if not, we should discuss further to be sure this will still meet your needs.

**Comment by dklawren** [comment]
> 
> 
> Hi @dklawren, we'd like to get additional context for the work that's driving this request. Gene asked the websre team to review and we aren't yet familiar with what's being done here, and I'm hoping you can help. Is there an upstream BMO issue, or a document or even just a Slack discussion, that we could review to gain a better understanding of this request?

Sure. Here are the related links that explain what is happening:
https://bugzilla.mozilla.org/show_bug.cgi?id=1612286
https://docs.google.com/document/d/1n9u6bQHmAXlDxpY78KTpFpSWIAhLyeyiK74Y4kf-zaE/edit?ts=5e424e27#heading=h.3o1jg7a1uy5s

> Also, a warning. This component of the IAM system is not designed to be resilient against transient errors, so we also need to confirm with you that it's acceptable for these RP notifications to be lossy. If you're already familiar with this concern, then that's a very brief confirmation; if not, we should discuss further to be sure this will still meet your needs.

That is fine and mentioned early on. I have a background process that also looks at accounts in BMO that are linked to IAM and will update if necessary periodically. The ping from CIS to BMO helps make the changes happen more quickly.

dkl

**Comment by dklawren** [comment]
Anything additional needed from me on this PR?

**Comment by floatingatoll** [comment]
I don't think there's anything else we're blocking on you for at this time, but we've run into some workflow issues that led to your request being dropped unintentionally — apologies about that. I also filed IAM-859 to see about repairing CI somehow, which may affect _all_ IAM commits — not just this one. We'll see.

**Review by floatingatoll — APPROVED** [review]
r+ from me, but I'm just working through my review requests backlog.

**Comment by dklawren** [comment]
Ping on this. I still need this to happen before we can turn on IAM support for BMO. Anything needed for this to to land and be deployed?

**Comment by dklawren** [comment]
Any way to get this merged and deployed? Seems everything is in order.

**Comment by dklawren** [comment]
> Hey @dklawren sorry about the delay here. While I read up on this request I do so one blocker we want to iron out first. Can you sign these commits? Our Github configuration will prevent me from merging until all the commits are signed.

Sure. Is it possible to sign an existing commit and push it to the PR or do I need to revert both commits and re-commit them with the -S switch? This is my first time signing commits.

**Comment by dklawren** [comment]
> You can rebase/squash and then sign the commits.

Sorry for the delay. I have now rebased and pushed the commits as GPG signed and verified.

**Review by bkochendorfer — APPROVED** [review]

**Comment by dklawren** [comment]
Is there an ETA on when this will be live in production?

**Comment by bkochendorfer** [comment]
@dklawren This was released shortly after it was merged, Jun 20th or so.

**Pull request merged**
