### PR TITLE
fix leeway for token expiration

### PR DESCRIPTION
**Pull request by fiji-flo**

### CODE REVIEW

**Comment by fiji-flo** [comment]
worked on my travis …
https://travis-ci.com/github/fiji-flo/cis/builds/164447122

**Comment by april** [comment]
This looks good to me, the only thing I might add is that since `expired` is only used inside this module, maybe the default leeway should be 910 instead of 0?

**Comment by gene1wood** [comment]
Travis builds are likely failing as reported in #492, not because of your changes

**Comment by fiji-flo** [comment]
@april I thought about making the default to 910, but I wanted this explicit in the line its used. But yeah, I get your point.

**Pull request merged**
